install(FILES easpanel-16x16.png DESTINATION share/icons/hicolor/16x16/apps/easpanel.png)
install(FILES easpanel-22x22.png DESTINATION share/icons/hicolor/22x22/apps/easpanel.png)
install(FILES easpanel-32x32.png DESTINATION share/icons/hicolor/32x32/apps/easpanel.png)
install(FILES easpanel-48x48.png DESTINATION share/icons/hicolor/48x48/apps/easpanel.png)
