; direct.conf
;
; This is the configuration file for EASPanel's direct file import
;  utility [directp(1)].
;

[Rivendell]
; IP address of Rivendell system
HostAddress=127.0.0.1

; The Rivendell User to use when creating/deleting carts
User=user

; The password for the Rivendell User
Password=

; The normalization level (in dBFS) to apply when importing audio.
; Use '0' to defeat normalization entirely.
NormalizationLevel=-11

; The auto-trim level (in dBFS) to apply when importing audio.
; Use '0' to defeat auto-trim entirely.
AutotrimLevel=0


[Paths]
; The UDP port number to listen on for messages from the 'rlm_easpanel' RLM.
; (It should seldom be necesssary to change this).
RlmReceivePort=2636


[DirectFile1]
Path=/path/to/file/location/file*.wav
;BackupDirectory=/path/to/directory/to/save/files
Description=Human-readable description
SchedulePolicy=immediate  ; Play immediately
;SchedulePolicy=next       ; Insert after currently playing item
;SchedulePolicy=ignore     ; Do nothing
;IntroCart=1234
;OutroCart=4321
AutomaticModeRml=LC red Weather Alerts Armed!
PausedModeRml=LB!

;[Easbelt1]
;SourceFiles=/var/eas/eas_*
;SftpIdentity=keyfile
;SftpUsername=username

;Destination1Hostname=hostname.example.com
;Destination1Path=/some/directory/on/hostname
;Destination1SftpIdentity=keyfile
;Destination1StpUsername=username


