; easbelt.conf
;
; This is the configuration file for the 'easbelt' file copying service.
;

;[Easbelt1]
;SourceFiles=/var/eas/eas_*
;SftpIdentity=keyfile
;SftpUsername=username

;Destination1Hostname=hostname.example.com
;Destination1Path=/some/directory/on/hostname
;Destination1SftpIdentity=keyfile
;Destination1StpUsername=username


